### ISSUE TITLE
문의 사항이 있습니다. 

### ISSUE THREAD

**Issue by byeolkady** [guitaristjimmy/kakao_arena#1]
song_vec = np.array(song_vec[0]) 이부분에서 NotImplementedError: Cannot convert a symbolic Tensor (strided_slice:0) to a numpy array. 해당오류가 뜨는데 어떻게 처리해야될지 알려주시면 감사하겠습니다.

**Comment by guitaristjimmy** [comment]
답장이 늦어서 죄송합니다..

우선 해당 부분에서 제가 실행할 때는 문제 없이 실행되는 것이 확인 되었는데,
혹시 keras 버전이 달라서 모델을 로드와 로드한 모델을 사용하는 부분에서 다른 점이 있어서 그런것이 아닌가 생각됩니다.
저는 tensorflow 2.1.0 버전에 포함된 keras를 사용했습니다.

이것이 문제가 아니라면,
제가 업로드 과정에서 모델을 실수로 잘못 올린것이 아닌가 생각됩니다...

아래의 링크를 통해서 모델을 다시 받아서 테스트해보시고 정상 작동된다면, 모델을 업로드 하는 과정에서 실수가 있었던 것 같습니다..
https://drive.google.com/file/d/1wB5MCDefHIzKhgUFToOBvf2nlvQbHO3e/view?usp=sharing


2020년 8월 7일 (금) 오후 5:23, byeolkady <notifications@github.com>님이 작성:

**Comment by byeolkady** [comment]
답장 주셔서 정말 감사드립니다. 
도움 주셔서 정말 감사합니다. 코드 보고 많은 도움이 되었습니다 .
